import "dotenv/config";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/ersan-diamond";
const R2 = "https://pub-2f86ee5ec40043559538f242150ae7b6.r2.dev/products";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

function daysFromNow(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d;
}

function img(slug: string, title: string) {
  return [
    { url: `${R2}/${slug}-1.jpg`, alt: `${title} - Front`, order: 0 },
    { url: `${R2}/${slug}-2.jpg`, alt: `${title} - Side`, order: 1 },
    { url: `${R2}/${slug}-3.jpg`, alt: `${title} - Back`, order: 2 },
  ];
}

// ---------------------------------------------------------------------------
// MAIN
// ---------------------------------------------------------------------------
async function seed() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("Connected.");

  const db = mongoose.connection.db!;

  // ── Clear existing data ──────────────────────────────────────────────
  const collections = [
    "users",
    "products",
    "leads",
    "appointments",
    "sales",
    "emailthreads",
    "emails",
    "calendarevents",
    "auditlogs",
  ];
  for (const col of collections) {
    try {
      await db.collection(col).drop();
    } catch {
      // Collection may not exist
    }
  }
  console.log("Cleared existing data.");

  // ── Users ────────────────────────────────────────────────────────────
  const ownerHash = await bcrypt.hash("ErsanDiamond2024!", 12);
  const owner = await db.collection("users").insertOne({
    name: "Ersan Bey",
    email: "ersan@ersandiamond.com",
    passwordHash: ownerHash,
    role: "OWNER",
    active: true,
    signatureName: "Ersan",
    signatureTitle: "Founder & CEO",
    phoneInternal: "+90 532 000 0000",
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  console.log("Created OWNER:", owner.insertedId);

  const adminHash = await bcrypt.hash("Admin2024!", 12);
  const admin = await db.collection("users").insertOne({
    name: "Ayşe Hanım",
    email: "ayse@ersandiamond.com",
    passwordHash: adminHash,
    role: "ADMIN",
    active: true,
    signatureName: "Ayşe",
    signatureTitle: "Concierge Manager",
    phoneInternal: "+90 533 000 0000",
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  console.log("Created ADMIN:", admin.insertedId);

  const salesHash = await bcrypt.hash("Sales2024!", 12);
  const sales = await db.collection("users").insertOne({
    name: "Yuşa Bey",
    email: "yusa@ersandiamond.com",
    passwordHash: salesHash,
    role: "SALES",
    active: true,
    signatureName: "Yuşa",
    signatureTitle: "Senior Sales Consultant",
    phoneInternal: "+90 534 000 0000",
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  console.log("Created SALES:", sales.insertedId);

  // ── Watches ──────────────────────────────────────────────────────────
  const watches = [
    // ── Rolex ──────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Rolex",
      model: "Submariner Date",
      reference: "126610LN",
      year: 2023,
      condition: "UNWORN",
      price: 18500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Rolex Submariner Date 126610LN",
      description:
        "The Oyster Perpetual Submariner Date in Oystersteel with a black Cerachrom bezel. Unworn condition with full box and papers.",
      specs: {
        caseSize: "41mm",
        caseMaterial: "Oystersteel",
        dialColor: "Black",
        bracelet: "Oyster",
        movement: "Automatic",
        caliber: "3235",
        waterResistance: "300m",
        boxPapers: "FULL_SET",
      },
      images: img("rolex-submariner-date-126610ln", "Rolex Submariner Date 126610LN"),
      slug: "rolex-submariner-date-126610ln",
      featured: true,
      published: true,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      category: "WATCH",
      brand: "Rolex",
      model: "Cosmograph Daytona",
      reference: "116500LN",
      year: 2022,
      condition: "EXCELLENT",
      price: 32000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Rolex Cosmograph Daytona 116500LN",
      description:
        "White dial Daytona with black ceramic bezel. Excellent condition, full set with warranty card dated 2022.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "Oystersteel",
        dialColor: "White",
        bracelet: "Oyster",
        movement: "Automatic",
        caliber: "4130",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("rolex-daytona-116500ln", "Rolex Cosmograph Daytona 116500LN"),
      slug: "rolex-daytona-116500ln",
      featured: true,
      published: true,
      createdAt: daysAgo(58),
      updatedAt: daysAgo(58),
    },
    {
      category: "WATCH",
      brand: "Rolex",
      model: "GMT-Master II",
      reference: "126710BLNR",
      year: 2023,
      condition: "UNWORN",
      price: 22500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Rolex GMT-Master II 126710BLNR",
      description:
        "The Batman GMT with blue and black Cerachrom bezel on Jubilee bracelet. Factory stickers still attached.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "Oystersteel",
        dialColor: "Black",
        bracelet: "Jubilee",
        movement: "Automatic",
        caliber: "3285",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("rolex-gmt-master-ii-126710blnr", "Rolex GMT-Master II 126710BLNR"),
      slug: "rolex-gmt-master-ii-126710blnr",
      featured: false,
      published: true,
      createdAt: daysAgo(55),
      updatedAt: daysAgo(55),
    },
    {
      category: "WATCH",
      brand: "Rolex",
      model: "Datejust 41",
      reference: "126334",
      year: 2021,
      condition: "VERY_GOOD",
      price: 14500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "RESERVED",
      title: "Rolex Datejust 41 126334",
      description:
        "Blue dial Datejust 41 with fluted bezel on Jubilee bracelet. Minor signs of wear, papers included.",
      specs: {
        caseSize: "41mm",
        caseMaterial: "Oystersteel / White Gold",
        dialColor: "Blue",
        bracelet: "Jubilee",
        movement: "Automatic",
        caliber: "3235",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("rolex-datejust-41-126334", "Rolex Datejust 41 126334"),
      slug: "rolex-datejust-41-126334",
      featured: false,
      published: true,
      createdAt: daysAgo(50),
      updatedAt: daysAgo(10),
    },

    // ── Patek Philippe ─────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Patek Philippe",
      model: "Nautilus",
      reference: "5711/1A-010",
      year: 2021,
      condition: "EXCELLENT",
      price: null,
      currency: "EUR",
      priceOnRequest: true,
      availability: "AVAILABLE",
      title: "Patek Philippe Nautilus 5711/1A-010",
      description:
        "The iconic discontinued Nautilus with blue dial. One of the most sought-after references in modern watchmaking.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Integrated Steel",
        movement: "Automatic",
        caliber: "26-330 S C",
        waterResistance: "120m",
        boxPapers: "FULL_SET",
      },
      images: img("patek-philippe-nautilus-5711-1a-010", "Patek Philippe Nautilus 5711/1A-010"),
      slug: "patek-philippe-nautilus-5711-1a-010",
      featured: true,
      published: true,
      createdAt: daysAgo(56),
      updatedAt: daysAgo(56),
    },
    {
      category: "WATCH",
      brand: "Patek Philippe",
      model: "Aquanaut",
      reference: "5167A-001",
      year: 2022,
      condition: "EXCELLENT",
      price: null,
      currency: "EUR",
      priceOnRequest: true,
      availability: "AVAILABLE",
      title: "Patek Philippe Aquanaut 5167A-001",
      description:
        "The sporty Aquanaut with embossed black dial and tropical composite strap. Excellent condition with full documentation.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Black",
        bracelet: "Composite Strap",
        movement: "Automatic",
        caliber: "324 S C",
        waterResistance: "120m",
        boxPapers: "FULL_SET",
      },
      images: img("patek-philippe-aquanaut-5167a-001", "Patek Philippe Aquanaut 5167A-001"),
      slug: "patek-philippe-aquanaut-5167a-001",
      featured: false,
      published: true,
      createdAt: daysAgo(52),
      updatedAt: daysAgo(52),
    },
    {
      category: "WATCH",
      brand: "Patek Philippe",
      model: "Calatrava",
      reference: "5227G-010",
      year: 2020,
      condition: "VERY_GOOD",
      price: 38000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Patek Philippe Calatrava 5227G-010",
      description:
        "A dress watch masterpiece in 18K white gold with an officer-style hinged caseback and silver opaline dial.",
      specs: {
        caseSize: "39mm",
        caseMaterial: "18K White Gold",
        dialColor: "Silver Opaline",
        bracelet: "Alligator Strap",
        movement: "Automatic",
        caliber: "324 S C",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img("patek-philippe-calatrava-5227g-010", "Patek Philippe Calatrava 5227G-010"),
      slug: "patek-philippe-calatrava-5227g-010",
      featured: false,
      published: true,
      createdAt: daysAgo(48),
      updatedAt: daysAgo(48),
    },

    // ── Audemars Piguet ────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Audemars Piguet",
      model: "Royal Oak",
      reference: "15500ST.OO.1220ST.01",
      year: 2022,
      condition: "VERY_GOOD",
      price: 42000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Audemars Piguet Royal Oak 15500ST",
      description:
        "Royal Oak Selfwinding 41mm in stainless steel with blue Grande Tapisserie dial. The quintessential luxury sports watch.",
      specs: {
        caseSize: "41mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Integrated Steel",
        movement: "Automatic",
        caliber: "4302",
        waterResistance: "50m",
        boxPapers: "FULL_SET",
      },
      images: img("audemars-piguet-royal-oak-15500st", "Audemars Piguet Royal Oak 15500ST"),
      slug: "audemars-piguet-royal-oak-15500st",
      featured: true,
      published: true,
      createdAt: daysAgo(54),
      updatedAt: daysAgo(54),
    },
    {
      category: "WATCH",
      brand: "Audemars Piguet",
      model: "Royal Oak Offshore",
      reference: "26470ST.OO.A027CA.01",
      year: 2021,
      condition: "EXCELLENT",
      price: 38000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Audemars Piguet Royal Oak Offshore 26470ST",
      description:
        "Royal Oak Offshore Chronograph 42mm with navy blue dial and rubber strap. Bold and sporty with excellent wrist presence.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Navy Blue",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "3126/3840",
        waterResistance: "100m",
        boxPapers: "BOX_ONLY",
      },
      images: img(
        "audemars-piguet-royal-oak-offshore-26470st",
        "Audemars Piguet Royal Oak Offshore 26470ST",
      ),
      slug: "audemars-piguet-royal-oak-offshore-26470st",
      featured: false,
      published: true,
      createdAt: daysAgo(47),
      updatedAt: daysAgo(47),
    },

    // ── Richard Mille ──────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Richard Mille",
      model: "RM 11-03",
      reference: "RM11-03",
      year: 2021,
      condition: "EXCELLENT",
      price: null,
      currency: "EUR",
      priceOnRequest: true,
      availability: "AVAILABLE",
      title: "Richard Mille RM 11-03 Automatic Flyback Chronograph",
      description:
        "Tonneau-shaped flyback chronograph in titanium. Skeletonized dial revealing the intricate RMAC3 movement.",
      specs: {
        caseSize: "49.94 x 44.50mm",
        caseMaterial: "Titanium",
        dialColor: "Skeletonized",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "RMAC3",
        waterResistance: "50m",
        boxPapers: "FULL_SET",
      },
      images: img("richard-mille-rm-11-03", "Richard Mille RM 11-03 Automatic Flyback Chronograph"),
      slug: "richard-mille-rm-11-03",
      featured: true,
      published: true,
      createdAt: daysAgo(45),
      updatedAt: daysAgo(45),
    },
    {
      category: "WATCH",
      brand: "Richard Mille",
      model: "RM 35-02",
      reference: "RM35-02",
      year: 2023,
      condition: "UNWORN",
      price: null,
      currency: "EUR",
      priceOnRequest: true,
      availability: "AVAILABLE",
      title: "Richard Mille RM 35-02 Rafael Nadal",
      description:
        "Ultra-lightweight automatic in NTPT Carbon. Designed for extreme sports, weighing only 40 grams including the strap.",
      specs: {
        caseSize: "49.94 x 44.50mm",
        caseMaterial: "NTPT Carbon",
        dialColor: "Skeletonized",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "RMAL1",
        waterResistance: "50m",
        boxPapers: "FULL_SET",
      },
      images: img("richard-mille-rm-35-02", "Richard Mille RM 35-02 Rafael Nadal"),
      slug: "richard-mille-rm-35-02",
      featured: false,
      published: true,
      createdAt: daysAgo(42),
      updatedAt: daysAgo(42),
    },

    // ── Vacheron Constantin ────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Vacheron Constantin",
      model: "Overseas",
      reference: "4500V/110A-B128",
      year: 2022,
      condition: "EXCELLENT",
      price: 35000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Vacheron Constantin Overseas 4500V/110A",
      description:
        "The Overseas Automatic 41mm with blue lacquered dial and interchangeable bracelet/strap system. Geneva Seal hallmark.",
      specs: {
        caseSize: "41mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Steel Bracelet + Rubber + Leather",
        movement: "Automatic",
        caliber: "5100",
        waterResistance: "150m",
        boxPapers: "FULL_SET",
      },
      images: img("vacheron-constantin-overseas-4500v", "Vacheron Constantin Overseas 4500V/110A"),
      slug: "vacheron-constantin-overseas-4500v",
      featured: false,
      published: true,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(40),
    },
    {
      category: "WATCH",
      brand: "Vacheron Constantin",
      model: "Patrimony",
      reference: "85180/000G-9230",
      year: 2020,
      condition: "VERY_GOOD",
      price: 28000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Vacheron Constantin Patrimony 85180/000G",
      description:
        "Timeless dress watch in 18K white gold with a silver-toned dial. Ultra-thin at only 8.1mm, hallmarked with the Geneva Seal.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "18K White Gold",
        dialColor: "Silver",
        bracelet: "Alligator Strap",
        movement: "Automatic",
        caliber: "2450 Q6",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img(
        "vacheron-constantin-patrimony-85180",
        "Vacheron Constantin Patrimony 85180/000G",
      ),
      slug: "vacheron-constantin-patrimony-85180",
      featured: false,
      published: true,
      createdAt: daysAgo(38),
      updatedAt: daysAgo(38),
    },

    // ── A. Lange & Söhne ───────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "A. Lange & Söhne",
      model: "Lange 1",
      reference: "191.032",
      year: 2021,
      condition: "EXCELLENT",
      price: 42000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "A. Lange & Söhne Lange 1 191.032",
      description:
        "The signature Lange 1 in 18K rose gold with an argenté dial and the iconic off-center time display. Manufactured in Glashütte.",
      specs: {
        caseSize: "38.5mm",
        caseMaterial: "18K Rose Gold",
        dialColor: "Argenté",
        bracelet: "Alligator Strap",
        movement: "Manual",
        caliber: "L121.1",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img("a-lange-sohne-lange-1-191032", "A. Lange & Söhne Lange 1 191.032"),
      slug: "a-lange-sohne-lange-1-191032",
      featured: false,
      published: true,
      createdAt: daysAgo(36),
      updatedAt: daysAgo(36),
    },
    {
      category: "WATCH",
      brand: "A. Lange & Söhne",
      model: "Saxonia Thin",
      reference: "211.032",
      year: 2020,
      condition: "VERY_GOOD",
      price: 19500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "A. Lange & Söhne Saxonia Thin 211.032",
      description:
        "Elegantly slim at 5.9mm in 18K rose gold with a copper-blue dial. Pure German haute horlogerie minimalism.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "18K Rose Gold",
        dialColor: "Copper Blue",
        bracelet: "Alligator Strap",
        movement: "Manual",
        caliber: "L093.1",
        waterResistance: "30m",
        boxPapers: "PAPERS_ONLY",
      },
      images: img("a-lange-sohne-saxonia-thin-211032", "A. Lange & Söhne Saxonia Thin 211.032"),
      slug: "a-lange-sohne-saxonia-thin-211032",
      featured: false,
      published: true,
      createdAt: daysAgo(34),
      updatedAt: daysAgo(34),
    },

    // ── Omega ──────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Omega",
      model: "Speedmaster Professional Moonwatch",
      reference: "310.30.42.50.01.001",
      year: 2023,
      condition: "UNWORN",
      price: 7800,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Omega Speedmaster Professional 310.30.42.50.01.001",
      description:
        "The legendary Moonwatch with the Co-Axial Master Chronometer caliber 3861. Hesalite crystal, full set with NASA-style box.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Black",
        bracelet: "Steel Bracelet",
        movement: "Manual",
        caliber: "3861",
        waterResistance: "50m",
        boxPapers: "FULL_SET",
      },
      images: img(
        "omega-speedmaster-professional-31030425001001",
        "Omega Speedmaster Professional 310.30.42.50.01.001",
      ),
      slug: "omega-speedmaster-professional-31030425001001",
      featured: true,
      published: true,
      createdAt: daysAgo(32),
      updatedAt: daysAgo(32),
    },
    {
      category: "WATCH",
      brand: "Omega",
      model: "Seamaster 300M",
      reference: "210.30.42.20.03.001",
      year: 2022,
      condition: "EXCELLENT",
      price: 5800,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Omega Seamaster 300M 210.30.42.20.03.001",
      description:
        "The James Bond diver with wave-pattern blue ceramic dial and ceramic bezel. Co-Axial Master Chronometer certified.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Steel Bracelet",
        movement: "Automatic",
        caliber: "8800",
        waterResistance: "300m",
        boxPapers: "FULL_SET",
      },
      images: img(
        "omega-seamaster-300m-21030422003001",
        "Omega Seamaster 300M 210.30.42.20.03.001",
      ),
      slug: "omega-seamaster-300m-21030422003001",
      featured: false,
      published: true,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(30),
    },

    // ── Cartier ────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Cartier",
      model: "Santos Medium",
      reference: "WSSA0029",
      year: 2023,
      condition: "UNWORN",
      price: 8200,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Cartier Santos Medium WSSA0029",
      description:
        "The redesigned Santos de Cartier in medium size with QuickSwitch bracelet/strap system and SmartLink adjustment.",
      specs: {
        caseSize: "35.1mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Silver",
        bracelet: "Steel Bracelet + Leather Strap",
        movement: "Automatic",
        caliber: "1847 MC",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("cartier-santos-medium-wssa0029", "Cartier Santos Medium WSSA0029"),
      slug: "cartier-santos-medium-wssa0029",
      featured: false,
      published: true,
      createdAt: daysAgo(28),
      updatedAt: daysAgo(28),
    },
    {
      category: "WATCH",
      brand: "Cartier",
      model: "Tank Française",
      reference: "WSTA0065",
      year: 2023,
      condition: "UNWORN",
      price: 9500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Cartier Tank Française WSTA0065",
      description:
        "The newly redesigned Tank Française in medium size. Seamlessly integrated bracelet with the signature Cartier silhouette.",
      specs: {
        caseSize: "32 x 27mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Silver",
        bracelet: "Steel Bracelet",
        movement: "Quartz",
        caliber: "N/A",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img("cartier-tank-francaise-wsta0065", "Cartier Tank Française WSTA0065"),
      slug: "cartier-tank-francaise-wsta0065",
      featured: false,
      published: true,
      createdAt: daysAgo(26),
      updatedAt: daysAgo(26),
    },

    // ── IWC ────────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "IWC",
      model: "Portugieser Chronograph",
      reference: "IW371605",
      year: 2022,
      condition: "EXCELLENT",
      price: 9200,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "IWC Portugieser Chronograph IW371605",
      description:
        "The Portugieser Chronograph with blue dial and gold-plated hands. One of IWC's most recognizable designs.",
      specs: {
        caseSize: "41mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Alligator Strap",
        movement: "Automatic",
        caliber: "69355",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img("iwc-portugieser-chronograph-iw371605", "IWC Portugieser Chronograph IW371605"),
      slug: "iwc-portugieser-chronograph-iw371605",
      featured: false,
      published: true,
      createdAt: daysAgo(24),
      updatedAt: daysAgo(24),
    },
    {
      category: "WATCH",
      brand: "IWC",
      model: "Pilot's Watch Mark XX",
      reference: "IW328203",
      year: 2023,
      condition: "UNWORN",
      price: 5600,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "IWC Pilot Mark XX IW328203",
      description:
        "The latest iteration of the iconic Mark series with a green dial. Features IWC's T-dial concept with matte finishing.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Green",
        bracelet: "Steel Bracelet",
        movement: "Automatic",
        caliber: "32111",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("iwc-pilot-mark-xx-iw328203", "IWC Pilot Mark XX IW328203"),
      slug: "iwc-pilot-mark-xx-iw328203",
      featured: false,
      published: true,
      createdAt: daysAgo(22),
      updatedAt: daysAgo(22),
    },

    // ── Jaeger-LeCoultre ───────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Jaeger-LeCoultre",
      model: "Reverso Classic Medium",
      reference: "Q2548440",
      year: 2021,
      condition: "EXCELLENT",
      price: 8500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Jaeger-LeCoultre Reverso Classic Medium Q2548440",
      description:
        "The Art Deco masterpiece with the iconic swiveling case. Silver dial with blued steel hands and Clous de Paris hobnail pattern.",
      specs: {
        caseSize: "40.1 x 24.4mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Silver",
        bracelet: "Leather Strap",
        movement: "Manual",
        caliber: "822/2",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img(
        "jaeger-lecoultre-reverso-classic-q2548440",
        "Jaeger-LeCoultre Reverso Classic Medium Q2548440",
      ),
      slug: "jaeger-lecoultre-reverso-classic-q2548440",
      featured: false,
      published: true,
      createdAt: daysAgo(20),
      updatedAt: daysAgo(20),
    },
    {
      category: "WATCH",
      brand: "Jaeger-LeCoultre",
      model: "Master Ultra Thin Moon",
      reference: "Q1368420",
      year: 2022,
      condition: "EXCELLENT",
      price: 12500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "SOLD",
      title: "Jaeger-LeCoultre Master Ultra Thin Moon Q1368420",
      description:
        "Ultra-thin moonphase complication in stainless steel with blue dial. Only 10.04mm thin despite housing a complete moonphase.",
      specs: {
        caseSize: "39mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Alligator Strap",
        movement: "Automatic",
        caliber: "925/1",
        waterResistance: "50m",
        boxPapers: "FULL_SET",
      },
      images: img(
        "jaeger-lecoultre-master-ultra-thin-moon-q1368420",
        "Jaeger-LeCoultre Master Ultra Thin Moon Q1368420",
      ),
      slug: "jaeger-lecoultre-master-ultra-thin-moon-q1368420",
      featured: false,
      published: true,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(5),
    },

    // ── Hublot ─────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Hublot",
      model: "Big Bang Unico",
      reference: "421.NM.1170.RX",
      year: 2023,
      condition: "UNWORN",
      price: 22000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hublot Big Bang Unico 421.NM.1170.RX",
      description:
        "Big Bang Unico 44mm in titanium with the in-house MHUB1280 UNICO movement visible through the skeletonized dial.",
      specs: {
        caseSize: "44mm",
        caseMaterial: "Titanium",
        dialColor: "Skeletonized",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "HUB1280",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("hublot-big-bang-unico-421nm1170rx", "Hublot Big Bang Unico 421.NM.1170.RX"),
      slug: "hublot-big-bang-unico-421nm1170rx",
      featured: false,
      published: true,
      createdAt: daysAgo(16),
      updatedAt: daysAgo(16),
    },
    {
      category: "WATCH",
      brand: "Hublot",
      model: "Classic Fusion",
      reference: "542.NX.1171.RX",
      year: 2022,
      condition: "VERY_GOOD",
      price: 8500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hublot Classic Fusion 542.NX.1171.RX",
      description:
        "Classic Fusion 42mm in titanium with sunray blue dial. The refined side of Hublot, perfect for dress or casual wear.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Titanium",
        dialColor: "Blue Sunray",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "HUB1110",
        waterResistance: "50m",
        boxPapers: "BOX_ONLY",
      },
      images: img(
        "hublot-classic-fusion-542nx1171rx",
        "Hublot Classic Fusion 542.NX.1171.RX",
      ),
      slug: "hublot-classic-fusion-542nx1171rx",
      featured: false,
      published: true,
      createdAt: daysAgo(14),
      updatedAt: daysAgo(14),
    },

    // ── Breguet ────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Breguet",
      model: "Classique",
      reference: "5177BB/29/9V6",
      year: 2021,
      condition: "EXCELLENT",
      price: 22000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Breguet Classique 5177BB/29/9V6",
      description:
        "The Classique 38mm in 18K white gold with a silvered gold dial featuring Clous de Paris guilloché and blued Breguet hands.",
      specs: {
        caseSize: "38mm",
        caseMaterial: "18K White Gold",
        dialColor: "Silver Guilloché",
        bracelet: "Leather Strap",
        movement: "Automatic",
        caliber: "777Q",
        waterResistance: "30m",
        boxPapers: "FULL_SET",
      },
      images: img("breguet-classique-5177bb", "Breguet Classique 5177BB/29/9V6"),
      slug: "breguet-classique-5177bb",
      featured: false,
      published: true,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(12),
    },
    {
      category: "WATCH",
      brand: "Breguet",
      model: "Marine",
      reference: "5517BB/Y2/9ZU",
      year: 2022,
      condition: "VERY_GOOD",
      price: 24000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Breguet Marine 5517BB/Y2/9ZU",
      description:
        "The Marine 40mm in 18K white gold with a blue gold dial and wave-engine guilloché. A modern interpretation of Breguet's naval heritage.",
      specs: {
        caseSize: "40mm",
        caseMaterial: "18K White Gold",
        dialColor: "Blue Guilloché",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "777Q",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("breguet-marine-5517bb", "Breguet Marine 5517BB/Y2/9ZU"),
      slug: "breguet-marine-5517bb",
      featured: false,
      published: true,
      createdAt: daysAgo(11),
      updatedAt: daysAgo(11),
    },

    // ── Panerai ────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Panerai",
      model: "Luminor Marina",
      reference: "PAM01312",
      year: 2023,
      condition: "UNWORN",
      price: 9800,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Panerai Luminor Marina PAM01312",
      description:
        "Luminor Marina 44mm in stainless steel with blue dial. Features the signature crown-protecting bridge and the in-house P.9010 caliber.",
      specs: {
        caseSize: "44mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Leather Strap",
        movement: "Automatic",
        caliber: "P.9010",
        waterResistance: "300m",
        boxPapers: "FULL_SET",
      },
      images: img("panerai-luminor-marina-pam01312", "Panerai Luminor Marina PAM01312"),
      slug: "panerai-luminor-marina-pam01312",
      featured: false,
      published: true,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
    {
      category: "WATCH",
      brand: "Panerai",
      model: "Submersible",
      reference: "PAM00973",
      year: 2021,
      condition: "GOOD",
      price: 11500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Panerai Submersible PAM00973",
      description:
        "Submersible 42mm in Carbotech with black dial. The lightweight carbon fiber composite case is virtually scratchproof.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Carbotech",
        dialColor: "Black",
        bracelet: "Rubber Strap",
        movement: "Automatic",
        caliber: "P.9010",
        waterResistance: "300m",
        boxPapers: "NONE",
      },
      images: img("panerai-submersible-pam00973", "Panerai Submersible PAM00973"),
      slug: "panerai-submersible-pam00973",
      featured: false,
      published: true,
      createdAt: daysAgo(9),
      updatedAt: daysAgo(9),
    },

    // ── Tudor ──────────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "Tudor",
      model: "Black Bay Fifty-Eight",
      reference: "M79030N-0001",
      year: 2023,
      condition: "UNWORN",
      price: 4200,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Tudor Black Bay Fifty-Eight M79030N",
      description:
        "The 39mm Black Bay Fifty-Eight in stainless steel with a black dial and bezel. A vintage-inspired diver that wears beautifully on any wrist.",
      specs: {
        caseSize: "39mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Black",
        bracelet: "Steel Bracelet",
        movement: "Automatic",
        caliber: "MT5402",
        waterResistance: "200m",
        boxPapers: "FULL_SET",
      },
      images: img("tudor-black-bay-fifty-eight-m79030n", "Tudor Black Bay Fifty-Eight M79030N"),
      slug: "tudor-black-bay-fifty-eight-m79030n",
      featured: false,
      published: true,
      createdAt: daysAgo(8),
      updatedAt: daysAgo(8),
    },
    {
      category: "WATCH",
      brand: "Tudor",
      model: "Pelagos",
      reference: "M25600TN-0001",
      year: 2022,
      condition: "EXCELLENT",
      price: 4800,
      currency: "EUR",
      priceOnRequest: false,
      availability: "RESERVED",
      title: "Tudor Pelagos M25600TN",
      description:
        "Professional diving watch rated to 500m in titanium with an in-house movement. Spring-loaded self-adjusting clasp for use over a wetsuit.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Titanium",
        dialColor: "Black",
        bracelet: "Titanium Bracelet",
        movement: "Automatic",
        caliber: "MT5612",
        waterResistance: "500m",
        boxPapers: "FULL_SET",
      },
      images: img("tudor-pelagos-m25600tn", "Tudor Pelagos M25600TN"),
      slug: "tudor-pelagos-m25600tn",
      featured: false,
      published: true,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(3),
    },

    // ── TAG Heuer ──────────────────────────────────────────────────────
    {
      category: "WATCH",
      brand: "TAG Heuer",
      model: "Carrera Chronograph",
      reference: "CBS2210.BA0917",
      year: 2023,
      condition: "UNWORN",
      price: 6800,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "TAG Heuer Carrera Chronograph CBS2210.BA0917",
      description:
        "The Carrera Chronograph with a blue dial and 3 sub-dials. A motor-racing inspired classic from TAG Heuer's flagship collection.",
      specs: {
        caseSize: "42mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Steel Bracelet",
        movement: "Automatic",
        caliber: "Heuer 02",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img(
        "tag-heuer-carrera-chronograph-cbs2210",
        "TAG Heuer Carrera Chronograph CBS2210.BA0917",
      ),
      slug: "tag-heuer-carrera-chronograph-cbs2210",
      featured: false,
      published: true,
      createdAt: daysAgo(6),
      updatedAt: daysAgo(6),
    },
    {
      category: "WATCH",
      brand: "TAG Heuer",
      model: "Monaco",
      reference: "CBL2111.BA0644",
      year: 2022,
      condition: "EXCELLENT",
      price: 7200,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "TAG Heuer Monaco CBL2111.BA0644",
      description:
        "The square-cased Monaco made famous by Steve McQueen. Blue dial chronograph with the Heuer 02 automatic movement.",
      specs: {
        caseSize: "39mm",
        caseMaterial: "Stainless Steel",
        dialColor: "Blue",
        bracelet: "Steel Bracelet",
        movement: "Automatic",
        caliber: "Heuer 02",
        waterResistance: "100m",
        boxPapers: "FULL_SET",
      },
      images: img("tag-heuer-monaco-cbl2111", "TAG Heuer Monaco CBL2111.BA0644"),
      slug: "tag-heuer-monaco-cbl2111",
      featured: false,
      published: true,
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
  ];

  // ── Hermès Products ──────────────────────────────────────────────────
  const hermes = [
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Birkin 25",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 28000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Birkin 25 Togo Noir GHW",
      description:
        "Brand new Birkin 25 in Togo leather, Noir colorway with Gold Hardware. Untouched and pristine with all accessories.",
      specs: {
        size: "25cm",
        material: "Togo Leather",
        color: "Noir",
        hardware: "Gold",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "Lock, Keys, Clochette, Raincoat",
      },
      images: img("hermes-birkin-25-togo-noir-ghw", "Hermès Birkin 25 Togo Noir GHW"),
      slug: "hermes-birkin-25-togo-noir-ghw",
      featured: true,
      published: true,
      createdAt: daysAgo(59),
      updatedAt: daysAgo(59),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Birkin 30",
      reference: "",
      year: 2022,
      condition: "EXCELLENT",
      price: 22000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Birkin 30 Clemence Etoupe PHW",
      description:
        "The versatile Birkin 30 in soft Clemence leather, the ever-popular Etoupe color with Palladium Hardware.",
      specs: {
        size: "30cm",
        material: "Clemence Leather",
        color: "Etoupe",
        hardware: "Palladium",
        stamp: "Y",
        dustbag: true,
        box: true,
        accessories: "Lock, Keys, Clochette, Raincoat",
      },
      images: img("hermes-birkin-30-clemence-etoupe-phw", "Hermès Birkin 30 Clemence Etoupe PHW"),
      slug: "hermes-birkin-30-clemence-etoupe-phw",
      featured: false,
      published: true,
      createdAt: daysAgo(57),
      updatedAt: daysAgo(57),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Birkin 35",
      reference: "",
      year: 2019,
      condition: "VERY_GOOD",
      price: 18000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Birkin 35 Togo Gold GHW",
      description:
        "Classic Birkin 35 in Togo Gold with Gold Hardware. The most iconic Hermès combination in a generously sized silhouette.",
      specs: {
        size: "35cm",
        material: "Togo Leather",
        color: "Gold",
        hardware: "Gold",
        stamp: "D",
        dustbag: true,
        box: true,
        accessories: "Lock, Keys, Clochette",
      },
      images: img("hermes-birkin-35-togo-gold-ghw", "Hermès Birkin 35 Togo Gold GHW"),
      slug: "hermes-birkin-35-togo-gold-ghw",
      featured: false,
      published: true,
      createdAt: daysAgo(53),
      updatedAt: daysAgo(53),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Kelly 25",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 32000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Kelly 25 Epsom Rose Sakura PHW",
      description:
        "A rare Kelly 25 Sellier in Rose Sakura Epsom with Palladium Hardware. The soft pink hue is one of the most coveted Hermès colors.",
      specs: {
        size: "25cm",
        material: "Epsom Leather",
        color: "Rose Sakura",
        hardware: "Palladium",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "Shoulder strap, Lock, Keys, Clochette, Raincoat",
      },
      images: img(
        "hermes-kelly-25-epsom-rose-sakura-phw",
        "Hermès Kelly 25 Epsom Rose Sakura PHW",
      ),
      slug: "hermes-kelly-25-epsom-rose-sakura-phw",
      featured: true,
      published: true,
      createdAt: daysAgo(51),
      updatedAt: daysAgo(51),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Kelly 28",
      reference: "",
      year: 2022,
      condition: "EXCELLENT",
      price: 22000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Kelly 28 Epsom Gold PHW",
      description:
        "Kelly 28 Sellier in Epsom leather, Gold colorway with Palladium Hardware. A timeless everyday companion.",
      specs: {
        size: "28cm",
        material: "Epsom Leather",
        color: "Gold",
        hardware: "Palladium",
        stamp: "Y",
        dustbag: true,
        box: true,
        accessories: "Shoulder strap, Lock, Keys, Clochette",
      },
      images: img("hermes-kelly-28-epsom-gold-phw", "Hermès Kelly 28 Epsom Gold PHW"),
      slug: "hermes-kelly-28-epsom-gold-phw",
      featured: true,
      published: true,
      createdAt: daysAgo(49),
      updatedAt: daysAgo(49),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Kelly 32",
      reference: "",
      year: 2020,
      condition: "VERY_GOOD",
      price: 18500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "RESERVED",
      title: "Hermès Kelly 32 Togo Noir GHW",
      description:
        "Kelly 32 Retourne in Togo Noir with Gold Hardware. The relaxed Retourne style in the classic black and gold combination.",
      specs: {
        size: "32cm",
        material: "Togo Leather",
        color: "Noir",
        hardware: "Gold",
        stamp: "X",
        dustbag: true,
        box: false,
        accessories: "Shoulder strap, Lock, Keys, Clochette",
      },
      images: img("hermes-kelly-32-togo-noir-ghw", "Hermès Kelly 32 Togo Noir GHW"),
      slug: "hermes-kelly-32-togo-noir-ghw",
      featured: false,
      published: true,
      createdAt: daysAgo(46),
      updatedAt: daysAgo(15),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Constance 24",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 35000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Constance 24 Epsom Rouge Casaque GHW",
      description:
        "Constance 24 in vibrant Rouge Casaque Epsom with Gold Hardware. The bold H-clasp makes an unmistakable statement.",
      specs: {
        size: "24cm",
        material: "Epsom Leather",
        color: "Rouge Casaque",
        hardware: "Gold",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "Shoulder strap",
      },
      images: img(
        "hermes-constance-24-epsom-rouge-casaque-ghw",
        "Hermès Constance 24 Epsom Rouge Casaque GHW",
      ),
      slug: "hermes-constance-24-epsom-rouge-casaque-ghw",
      featured: true,
      published: true,
      createdAt: daysAgo(43),
      updatedAt: daysAgo(43),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Picotin Lock 18",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 10500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Picotin Lock 18 Clemence Etoupe PHW",
      description:
        "The charming Picotin Lock 18 in Clemence Etoupe with Palladium Hardware. A delightfully casual and functional open-top bag.",
      specs: {
        size: "18cm",
        material: "Clemence Leather",
        color: "Etoupe",
        hardware: "Palladium",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "Lock",
      },
      images: img(
        "hermes-picotin-lock-18-clemence-etoupe-phw",
        "Hermès Picotin Lock 18 Clemence Etoupe PHW",
      ),
      slug: "hermes-picotin-lock-18-clemence-etoupe-phw",
      featured: false,
      published: true,
      createdAt: daysAgo(41),
      updatedAt: daysAgo(41),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Evelyne PM",
      reference: "",
      year: 2022,
      condition: "EXCELLENT",
      price: 5500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Evelyne PM Clemence Noir GHW",
      description:
        "Evelyne III PM 29 in Clemence Noir with Gold Hardware. The perforated H logo and adjustable strap make it an effortless crossbody.",
      specs: {
        size: "29cm",
        material: "Clemence Leather",
        color: "Noir",
        hardware: "Gold",
        stamp: "Y",
        dustbag: true,
        box: false,
        accessories: "Shoulder strap",
      },
      images: img("hermes-evelyne-pm-clemence-noir-ghw", "Hermès Evelyne PM Clemence Noir GHW"),
      slug: "hermes-evelyne-pm-clemence-noir-ghw",
      featured: false,
      published: true,
      createdAt: daysAgo(39),
      updatedAt: daysAgo(39),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Lindy 26",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 14000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Lindy 26 Clemence Bleu Nuit PHW",
      description:
        "Lindy 26 in Clemence Bleu Nuit with Palladium Hardware. A unique double-handle design that can be worn as a shoulder bag or handbag.",
      specs: {
        size: "26cm",
        material: "Clemence Leather",
        color: "Bleu Nuit",
        hardware: "Palladium",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "Shoulder strap",
      },
      images: img(
        "hermes-lindy-26-clemence-bleu-nuit-phw",
        "Hermès Lindy 26 Clemence Bleu Nuit PHW",
      ),
      slug: "hermes-lindy-26-clemence-bleu-nuit-phw",
      featured: false,
      published: true,
      createdAt: daysAgo(37),
      updatedAt: daysAgo(37),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Bolide 31",
      reference: "",
      year: 2022,
      condition: "EXCELLENT",
      price: 11000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Bolide 31 Epsom Craie GHW",
      description:
        "Bolide 31 in Epsom Craie with Gold Hardware. The world's first zippered bag, elegant and understated in creamy white.",
      specs: {
        size: "31cm",
        material: "Epsom Leather",
        color: "Craie",
        hardware: "Gold",
        stamp: "Y",
        dustbag: true,
        box: true,
        accessories: "Shoulder strap, Lock, Keys, Clochette",
      },
      images: img("hermes-bolide-31-epsom-craie-ghw", "Hermès Bolide 31 Epsom Craie GHW"),
      slug: "hermes-bolide-31-epsom-craie-ghw",
      featured: false,
      published: true,
      createdAt: daysAgo(35),
      updatedAt: daysAgo(35),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Garden Party 36",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 4200,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Garden Party 36 Negonda Noir",
      description:
        "Garden Party 36 in Negonda Noir. A spacious everyday tote with a relaxed, unstructured silhouette and leather handles.",
      specs: {
        size: "36cm",
        material: "Negonda Leather",
        color: "Noir",
        hardware: "N/A",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "N/A",
      },
      images: img("hermes-garden-party-36-negonda-noir", "Hermès Garden Party 36 Negonda Noir"),
      slug: "hermes-garden-party-36-negonda-noir",
      featured: false,
      published: true,
      createdAt: daysAgo(33),
      updatedAt: daysAgo(33),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Herbag Zip 31",
      reference: "",
      year: 2023,
      condition: "UNWORN",
      price: 4800,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Hermès Herbag Zip 31 Toile/Hunter Noir",
      description:
        "Herbag Zip 31 in Toile and Hunter leather, Noir. A versatile two-in-one bag with interchangeable canvas pouches.",
      specs: {
        size: "31cm",
        material: "Toile / Hunter Leather",
        color: "Noir",
        hardware: "Palladium",
        stamp: "Z",
        dustbag: true,
        box: true,
        accessories: "Removable pouch",
      },
      images: img(
        "hermes-herbag-zip-31-toile-hunter-noir",
        "Hermès Herbag Zip 31 Toile/Hunter Noir",
      ),
      slug: "hermes-herbag-zip-31-toile-hunter-noir",
      featured: false,
      published: true,
      createdAt: daysAgo(31),
      updatedAt: daysAgo(31),
    },
    {
      category: "HERMES",
      brand: "Hermès",
      model: "Halzan 31",
      reference: "",
      year: 2022,
      condition: "EXCELLENT",
      price: 12000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "SOLD",
      title: "Hermès Halzan 31 Clemence Vert Amande PHW",
      description:
        "Halzan 31 in Clemence Vert Amande with Palladium Hardware. A convertible bag that transforms from tote to crossbody in seconds.",
      specs: {
        size: "31cm",
        material: "Clemence Leather",
        color: "Vert Amande",
        hardware: "Palladium",
        stamp: "Y",
        dustbag: true,
        box: true,
        accessories: "Shoulder strap",
      },
      images: img(
        "hermes-halzan-31-clemence-vert-amande-phw",
        "Hermès Halzan 31 Clemence Vert Amande PHW",
      ),
      slug: "hermes-halzan-31-clemence-vert-amande-phw",
      featured: false,
      published: true,
      createdAt: daysAgo(29),
      updatedAt: daysAgo(8),
    },
  ];

  // ── Jewelry Products ─────────────────────────────────────────────────
  const jewelry = [
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Diamond Solitaire Ring 2ct",
      reference: "EDC-SR-200",
      year: 2024,
      condition: "UNWORN",
      price: 32000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Diamond Solitaire Ring 2ct D/IF 18K White Gold",
      description:
        "A stunning 2-carat round brilliant diamond solitaire in 18K white gold. GIA certified D color, Internally Flawless clarity.",
      specs: {
        type: "Yüzük",
        metal: "18K White Gold",
        gemstone: "Diamond",
        carat: "2.00ct",
        size: "54 (EU) / 6.75 (US)",
        weight: "4.8g",
        certification: "GIA 2235468901",
      },
      images: img("diamond-solitaire-ring-2ct-d-if-18k-white-gold", "Diamond Solitaire Ring 2ct D/IF 18K White Gold"),
      slug: "diamond-solitaire-ring-2ct-d-if-18k-white-gold",
      featured: true,
      published: true,
      createdAt: daysAgo(44),
      updatedAt: daysAgo(44),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Diamond Tennis Bracelet 5ct",
      reference: "EDC-TB-500",
      year: 2024,
      condition: "UNWORN",
      price: 18000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Diamond Tennis Bracelet 5ct 18K White Gold",
      description:
        "Classic tennis bracelet with 5 carats of round brilliant diamonds set in 18K white gold. Prong-set with safety clasp.",
      specs: {
        type: "Bilezik",
        metal: "18K White Gold",
        gemstone: "Diamond",
        carat: "5.00ct total",
        size: "18cm",
        weight: "12.5g",
        certification: "GIA",
      },
      images: img(
        "diamond-tennis-bracelet-5ct-18k-white-gold",
        "Diamond Tennis Bracelet 5ct 18K White Gold",
      ),
      slug: "diamond-tennis-bracelet-5ct-18k-white-gold",
      featured: true,
      published: true,
      createdAt: daysAgo(42),
      updatedAt: daysAgo(42),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Diamond Pendant Necklace 1.5ct",
      reference: "EDC-PN-150",
      year: 2024,
      condition: "UNWORN",
      price: 14000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Diamond Pendant Necklace 1.5ct 18K Yellow Gold",
      description:
        "Elegant solitaire pendant with a 1.5-carat pear-shaped diamond on an 18K yellow gold chain. GIA certified E/VS1.",
      specs: {
        type: "Kolye",
        metal: "18K Yellow Gold",
        gemstone: "Diamond",
        carat: "1.50ct",
        size: "42cm chain",
        weight: "5.2g",
        certification: "GIA 6234789012",
      },
      images: img(
        "diamond-pendant-necklace-1-5ct-18k-yellow-gold",
        "Diamond Pendant Necklace 1.5ct 18K Yellow Gold",
      ),
      slug: "diamond-pendant-necklace-1-5ct-18k-yellow-gold",
      featured: false,
      published: true,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(40),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Emerald & Diamond Ring 3ct",
      reference: "EDC-ER-300",
      year: 2023,
      condition: "UNWORN",
      price: 38000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Emerald & Diamond Ring 3ct 18K Yellow Gold",
      description:
        "Exceptional 3-carat Colombian emerald flanked by two trapezoid diamonds in 18K yellow gold. GRS certified with minor oil treatment.",
      specs: {
        type: "Yüzük",
        metal: "18K Yellow Gold",
        gemstone: "Emerald + Diamond",
        carat: "3.00ct emerald / 0.80ct diamonds",
        size: "53 (EU) / 6.5 (US)",
        weight: "6.1g",
        certification: "GRS 2023-031245",
      },
      images: img(
        "emerald-diamond-ring-3ct-18k-yellow-gold",
        "Emerald & Diamond Ring 3ct 18K Yellow Gold",
      ),
      slug: "emerald-diamond-ring-3ct-18k-yellow-gold",
      featured: true,
      published: true,
      createdAt: daysAgo(38),
      updatedAt: daysAgo(38),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Ruby Stud Earrings 2ct",
      reference: "EDC-RE-200",
      year: 2023,
      condition: "UNWORN",
      price: 12000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Ruby Stud Earrings 2ct 18K Rose Gold",
      description:
        "Matched pair of oval Burmese rubies totaling 2 carats, each surrounded by a diamond halo, set in 18K rose gold.",
      specs: {
        type: "Küpe",
        metal: "18K Rose Gold",
        gemstone: "Ruby + Diamond",
        carat: "2.00ct rubies / 0.40ct diamonds",
        size: "10mm diameter",
        weight: "3.8g",
        certification: "Gübelin",
      },
      images: img("ruby-stud-earrings-2ct-18k-rose-gold", "Ruby Stud Earrings 2ct 18K Rose Gold"),
      slug: "ruby-stud-earrings-2ct-18k-rose-gold",
      featured: false,
      published: true,
      createdAt: daysAgo(36),
      updatedAt: daysAgo(36),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Sapphire Solitaire Necklace 4ct",
      reference: "EDC-SN-400",
      year: 2023,
      condition: "UNWORN",
      price: 45000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Sapphire Solitaire Necklace 4ct Platinum",
      description:
        "A magnificent 4-carat Ceylon sapphire pendant in platinum with diamond bail. Vivid royal blue with no heat treatment.",
      specs: {
        type: "Kolye",
        metal: "Platinum",
        gemstone: "Sapphire + Diamond",
        carat: "4.00ct sapphire / 0.30ct diamonds",
        size: "45cm chain",
        weight: "8.5g",
        certification: "SSEF",
      },
      images: img("sapphire-solitaire-necklace-4ct-platinum", "Sapphire Solitaire Necklace 4ct Platinum"),
      slug: "sapphire-solitaire-necklace-4ct-platinum",
      featured: false,
      published: true,
      createdAt: daysAgo(34),
      updatedAt: daysAgo(34),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "South Sea Pearl Set",
      reference: "EDC-PS-001",
      year: 2024,
      condition: "UNWORN",
      price: 22000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "South Sea Pearl Necklace & Earring Set",
      description:
        "Matched South Sea pearl set: graduated necklace of 33 pearls (11-15mm) with diamond clasp, and matching drop earrings in 18K white gold.",
      specs: {
        type: "Set",
        metal: "18K White Gold",
        gemstone: "South Sea Pearl + Diamond",
        carat: "0.50ct diamonds",
        size: "Necklace 45cm / Earrings 35mm drop",
        weight: "85g total",
        certification: "N/A",
      },
      images: img(
        "south-sea-pearl-necklace-earring-set",
        "South Sea Pearl Necklace & Earring Set",
      ),
      slug: "south-sea-pearl-necklace-earring-set",
      featured: false,
      published: true,
      createdAt: daysAgo(32),
      updatedAt: daysAgo(32),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Diamond Eternity Band 2ct",
      reference: "EDC-EB-200",
      year: 2024,
      condition: "UNWORN",
      price: 8500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Diamond Eternity Band 2ct Platinum",
      description:
        "Full eternity band with 2 carats of round brilliant diamonds channel-set in platinum. Perfect as a wedding band or stack ring.",
      specs: {
        type: "Yüzük",
        metal: "Platinum",
        gemstone: "Diamond",
        carat: "2.00ct total",
        size: "52 (EU) / 6 (US)",
        weight: "4.2g",
        certification: "GIA",
      },
      images: img("diamond-eternity-band-2ct-platinum", "Diamond Eternity Band 2ct Platinum"),
      slug: "diamond-eternity-band-2ct-platinum",
      featured: false,
      published: true,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(30),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Diamond Stud Earrings 3ct",
      reference: "EDC-DE-300",
      year: 2024,
      condition: "UNWORN",
      price: 42000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "RESERVED",
      title: "Diamond Stud Earrings 3ct 18K White Gold",
      description:
        "Matched pair of round brilliant diamonds totaling 3 carats (1.50ct each) in 18K white gold four-prong martini settings. GIA certified F/VS1.",
      specs: {
        type: "Küpe",
        metal: "18K White Gold",
        gemstone: "Diamond",
        carat: "3.00ct total (2 x 1.50ct)",
        size: "7.3mm diameter each",
        weight: "2.8g",
        certification: "GIA 1234567890 / GIA 0987654321",
      },
      images: img(
        "diamond-stud-earrings-3ct-18k-white-gold",
        "Diamond Stud Earrings 3ct 18K White Gold",
      ),
      slug: "diamond-stud-earrings-3ct-18k-white-gold",
      featured: false,
      published: true,
      createdAt: daysAgo(28),
      updatedAt: daysAgo(4),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Italian Gold Chain Necklace",
      reference: "EDC-GC-001",
      year: 2024,
      condition: "UNWORN",
      price: 5200,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Italian Gold Chain Necklace 18K Yellow Gold",
      description:
        "Hand-crafted Italian curb-link chain in solid 18K yellow gold. A substantial everyday statement piece at 50cm length.",
      specs: {
        type: "Kolye",
        metal: "18K Yellow Gold",
        gemstone: "N/A",
        carat: "N/A",
        size: "50cm",
        weight: "28g",
        certification: "Italian Hallmark 750",
      },
      images: img(
        "italian-gold-chain-necklace-18k-yellow-gold",
        "Italian Gold Chain Necklace 18K Yellow Gold",
      ),
      slug: "italian-gold-chain-necklace-18k-yellow-gold",
      featured: false,
      published: true,
      createdAt: daysAgo(26),
      updatedAt: daysAgo(26),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Diamond & Emerald Brooch",
      reference: "EDC-BR-001",
      year: 2023,
      condition: "EXCELLENT",
      price: 15000,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Diamond & Emerald Brooch 18K White Gold",
      description:
        "Art Deco-inspired brooch featuring a 1.5ct emerald center stone surrounded by 2ct of baguette and brilliant-cut diamonds in 18K white gold.",
      specs: {
        type: "Broş",
        metal: "18K White Gold",
        gemstone: "Emerald + Diamond",
        carat: "1.50ct emerald / 2.00ct diamonds",
        size: "45 x 30mm",
        weight: "14g",
        certification: "N/A",
      },
      images: img(
        "diamond-emerald-brooch-18k-white-gold",
        "Diamond & Emerald Brooch 18K White Gold",
      ),
      slug: "diamond-emerald-brooch-18k-white-gold",
      featured: false,
      published: true,
      createdAt: daysAgo(24),
      updatedAt: daysAgo(24),
    },
    {
      category: "JEWELRY",
      brand: "Ersan Diamond Collection",
      model: "Multi-gem Tennis Bracelet",
      reference: "EDC-MT-001",
      year: 2024,
      condition: "UNWORN",
      price: 16500,
      currency: "EUR",
      priceOnRequest: false,
      availability: "AVAILABLE",
      title: "Multi-gem Tennis Bracelet 18K Rose Gold",
      description:
        "A rainbow tennis bracelet with alternating rubies, sapphires, emeralds, and diamonds totaling 6ct in 18K rose gold. A modern statement piece.",
      specs: {
        type: "Bilezik",
        metal: "18K Rose Gold",
        gemstone: "Ruby + Sapphire + Emerald + Diamond",
        carat: "6.00ct total",
        size: "18cm",
        weight: "15g",
        certification: "N/A",
      },
      images: img(
        "multi-gem-tennis-bracelet-18k-rose-gold",
        "Multi-gem Tennis Bracelet 18K Rose Gold",
      ),
      slug: "multi-gem-tennis-bracelet-18k-rose-gold",
      featured: false,
      published: true,
      createdAt: daysAgo(22),
      updatedAt: daysAgo(22),
    },
  ];

  // ── Insert all products ──────────────────────────────────────────────
  const allProducts = [...watches, ...hermes, ...jewelry];
  await db.collection("products").insertMany(allProducts);
  console.log(`Created ${allProducts.length} products (${watches.length} watches, ${hermes.length} Hermès, ${jewelry.length} jewelry).`);

  // ── Leads ────────────────────────────────────────────────────────────
  const leads = [
    {
      type: "INQUIRY",
      name: "Mehmet Yılmaz",
      phone: "+90 532 111 2233",
      email: "mehmet.yilmaz@example.com",
      source: "WEBSITE",
      notes: "Interested in Rolex Submariner, prefers full set unworn.",
      status: "NEW",
      assignedUserId: sales.insertedId,
      tags: ["watch", "rolex"],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
    {
      type: "SELL_TO_US",
      name: "Fatma Demir",
      phone: "+90 533 444 5566",
      email: "fatma.demir@example.com",
      source: "WHATSAPP",
      notes: "Wants to sell her Birkin 30 Etoupe. Claims excellent condition, has full set.",
      status: "CONTACTED",
      assignedUserId: sales.insertedId,
      productBrand: "Hermès",
      productModel: "Birkin 30",
      productCondition: "EXCELLENT",
      desiredPrice: 20000,
      currency: "EUR",
      tags: ["hermes", "sell"],
      createdAt: daysAgo(4),
      updatedAt: daysAgo(3),
    },
    {
      type: "INQUIRY",
      name: "Ali Kaya",
      phone: "+90 535 777 8899",
      email: "ali.kaya@example.com",
      source: "REFERRAL",
      notes: "Looking for Patek Nautilus or Aquanaut. Budget flexible, wants the best available.",
      status: "QUALIFIED",
      assignedUserId: sales.insertedId,
      tags: ["watch", "patek-philippe", "high-value"],
      createdAt: daysAgo(7),
      updatedAt: daysAgo(2),
    },
    {
      type: "SELL_TO_US",
      name: "Zeynep Arslan",
      phone: "+90 536 222 3344",
      email: "zeynep.arslan@example.com",
      source: "WEBSITE",
      notes: "Selling AP Royal Oak 15500ST blue dial. Has box but not papers.",
      status: "PROPOSAL",
      assignedUserId: sales.insertedId,
      productBrand: "Audemars Piguet",
      productModel: "Royal Oak",
      productReference: "15500ST",
      productYear: 2021,
      productCondition: "VERY_GOOD",
      desiredPrice: 35000,
      currency: "EUR",
      tags: ["watch", "ap", "sell"],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
    {
      type: "INQUIRY",
      name: "Burak Özdemir",
      phone: "+90 537 999 0011",
      email: "burak.ozdemir@example.com",
      source: "WALK_IN",
      notes: "Walked in looking for a 2ct diamond engagement ring. Wants GIA certified, D-F color.",
      status: "CONTACTED",
      assignedUserId: sales.insertedId,
      tags: ["jewelry", "diamond", "engagement"],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
    },
    {
      type: "SELL_TO_US",
      name: "Selin Çelik",
      phone: "+90 538 333 4455",
      email: "selin.celik@example.com",
      source: "WHATSAPP",
      notes: "Has a Richard Mille RM 11-03 she inherited. Wants a valuation.",
      status: "NEW",
      assignedUserId: sales.insertedId,
      productBrand: "Richard Mille",
      productModel: "RM 11-03",
      productCondition: "GOOD",
      tags: ["watch", "richard-mille", "sell", "high-value"],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ];

  await db.collection("leads").insertMany(leads);
  console.log(`Created ${leads.length} leads.`);

  // ── Appointments ─────────────────────────────────────────────────────
  const appointments = [
    {
      customerName: "Ali Kaya",
      customerPhone: "+90 535 777 8899",
      customerEmail: "ali.kaya@example.com",
      serviceType: "IN_STORE",
      datetimeStart: daysFromNow(3),
      datetimeEnd: new Date(daysFromNow(3).getTime() + 60 * 60 * 1000), // +1 hour
      status: "CONFIRMED",
      assignedUserId: sales.insertedId,
      notes: "Wants to see Patek Philippe Nautilus and Aquanaut in person.",
      reminderSent24h: false,
      reminderSent2h: false,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      customerName: "Burak Özdemir",
      customerPhone: "+90 537 999 0011",
      customerEmail: "burak.ozdemir@example.com",
      serviceType: "VIDEO_CALL",
      datetimeStart: daysFromNow(5),
      datetimeEnd: new Date(daysFromNow(5).getTime() + 30 * 60 * 1000), // +30 min
      status: "PENDING",
      assignedUserId: sales.insertedId,
      notes: "Video call to discuss diamond ring options and see certificates.",
      reminderSent24h: false,
      reminderSent2h: false,
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      customerName: "Derya Şahin",
      customerPhone: "+90 539 666 7788",
      customerEmail: "derya.sahin@example.com",
      serviceType: "SOURCING",
      datetimeStart: daysFromNow(7),
      datetimeEnd: new Date(daysFromNow(7).getTime() + 45 * 60 * 1000), // +45 min
      status: "CONFIRMED",
      assignedUserId: sales.insertedId,
      notes: "Looking for a specific Hermès Kelly 25 in Rose Confetti. Sourcing consultation.",
      reminderSent24h: false,
      reminderSent2h: false,
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ];

  await db.collection("appointments").insertMany(appointments);
  console.log(`Created ${appointments.length} appointments.`);

  // ── Indexes ──────────────────────────────────────────────────────────
  await db.collection("users").createIndex({ email: 1 }, { unique: true });
  await db.collection("users").createIndex({ role: 1 });
  await db.collection("products").createIndex({ slug: 1 }, { unique: true });
  await db.collection("products").createIndex({ category: 1, availability: 1 });
  await db.collection("products").createIndex({ brand: 1, model: 1 });
  await db.collection("products").createIndex({ featured: 1, createdAt: -1 });
  await db.collection("products").createIndex({ published: 1, createdAt: -1 });
  await db.collection("products").createIndex({ price: 1 });
  await db.collection("leads").createIndex({ status: 1, assignedUserId: 1 });
  await db.collection("leads").createIndex({ email: 1 });
  await db.collection("leads").createIndex({ createdAt: -1 });
  await db.collection("appointments").createIndex({ datetimeStart: 1, status: 1 });
  await db.collection("appointments").createIndex({ assignedUserId: 1, datetimeStart: 1 });
  await db.collection("appointments").createIndex({ customerEmail: 1 });
  await db.collection("sales").createIndex({ createdAt: -1 });
  await db.collection("sales").createIndex({ productId: 1 });
  await db.collection("sales").createIndex({ salesRepId: 1 });
  await db.collection("emailthreads").createIndex({ customerEmail: 1 });
  await db.collection("emailthreads").createIndex({ lastMessageAt: -1 });
  await db.collection("emails").createIndex({ threadId: 1, sentAt: 1 });
  await db.collection("calendarevents").createIndex({ ownerUserId: 1, start: 1 });
  await db.collection("auditlogs").createIndex({ createdAt: -1 });
  await db.collection("auditlogs").createIndex({ createdAt: 1 }, { expireAfterSeconds: 7776000 }); // 90 days TTL
  console.log("Created indexes.");

  // ── Summary ──────────────────────────────────────────────────────────
  console.log("\n========================================");
  console.log("  SEED COMPLETED SUCCESSFULLY");
  console.log("========================================\n");
  console.log("Entities created:");
  console.log(`  Users:        3`);
  console.log(`  Watches:      ${watches.length}`);
  console.log(`  Hermès:       ${hermes.length}`);
  console.log(`  Jewelry:      ${jewelry.length}`);
  console.log(`  Products:     ${allProducts.length} total`);
  console.log(`  Leads:        ${leads.length}`);
  console.log(`  Appointments: ${appointments.length}`);
  console.log("");
  console.log("Login credentials:");
  console.log("  OWNER: ersan@ersandiamond.com / ErsanDiamond2024!");
  console.log("  ADMIN: ayse@ersandiamond.com / Admin2024!");
  console.log("  SALES: yusa@ersandiamond.com / Sales2024!");
  console.log("");

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
